"""empty message

Revision ID: 94d569939fb1
Revises: 9e64e7110762
Create Date: 2023-07-11 15:16:33.680946

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94d569939fb1'
down_revision = '9e64e7110762'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blocks', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_doc_page_blocknum', ['doc_id', 'page_id', 'block_num'])

    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_path', ['path'])
        batch_op.create_unique_constraint(None, ['path'])

    with op.batch_alter_table('pages', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_doc_pagenum', ['doc_id', 'page_num'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pages', schema=None) as batch_op:
        batch_op.drop_constraint('unique_doc_pagenum', type_='unique')

    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint('unique_path', type_='unique')

    with op.batch_alter_table('blocks', schema=None) as batch_op:
        batch_op.drop_constraint('unique_doc_page_blocknum', type_='unique')

    # ### end Alembic commands ###
