"""empty message

Revision ID: 9e64e7110762
Revises: 27cc61d73991
Create Date: 2023-07-10 16:26:48.485922

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e64e7110762'
down_revision = '27cc61d73991'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('x0', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('x1', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('y0', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('y1', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pages', schema=None) as batch_op:
        batch_op.drop_column('y1')
        batch_op.drop_column('y0')
        batch_op.drop_column('x1')
        batch_op.drop_column('x0')

    # ### end Alembic commands ###
