"""empty message

Revision ID: a7fa18c9c2c7
Revises: 97b4a3bd818f
Create Date: 2023-07-07 20:26:48.744632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7fa18c9c2c7'
down_revision = '97b4a3bd818f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('doc_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'documents', ['doc_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pages', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('doc_id')

    # ### end Alembic commands ###
